var a=[]
var b1=prompt("enter your favourite book")
a.push(b1)
var b2=prompt("enter the author name")
a.push(b2)
var b3=prompt("which edition is this")
a.push(b3)
var b4=prompt("what is your second favourite book")
a.push(b4)
var b5=prompt("whois author of this book")
a.push(b5)
var b6=prompt("what is the meaning of novel")
a.unshift(b6)
a.pop()
console.log(a)
